# 'path' resolve os caminhos para 'val' e 'test'.
path: /mnt/gustavo/active-vehicle-detection/treino_transitar

# Para 'train', usamos um caminho absoluto para evitar qualquer ambiguidade.
train: /mnt/gustavo/active-vehicle-detection/tt_balance/config/ciclo_2/labeled.txt
val: val/images

nc: 8
# Definição das Classes
names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: airplane
  5: bus
  6: van
  7: truck